name: WAF IPsets display
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2 #default
          verbose: false # default
          arch: amd64 # allowed values: amd64, arm64
          rootdir: "" # defaults to "PWD"
          workdir: "" # defaults to "PWD/unfor19-awscli"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get WAF IPsets
        run: |
          output=$(aws wafv2 list-ip-sets --scope CLOUDFRONT --region us-east-1)
          blocked_id=$(echo "$output" | jq -r '.IPSets[] | select(.Name=="Blocked") | .Id')
          whitelist_id=$(echo "$output" | jq -r '.IPSets[] | select(.Name=="WhiteList") | .Id')
          blocked_addresses=$(aws wafv2 get-ip-set --scope CLOUDFRONT --region us-east-1 --name Blocked --id $blocked_id | jq -r '.IPSet.Addresses')
          whitelist_addresses=$(aws wafv2 get-ip-set --scope CLOUDFRONT --region us-east-1 --name WhiteList --id $whitelist_id | jq -r '.IPSet.Addresses')
          json_output="{\"Blocked\": $blocked_addresses, \"WhiteList\": $whitelist_addresses}"
          echo $json_output > dev.json
          cp -fr dev.json drawer-app/src

      - name: Publish react app on Github Pages
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          checkout: false
          build_command: |
            cd drawer-app
            CI=false
            npm install --force
            npm run build
          path: drawer-app/build
