name: WAF IPsets display
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2 #default
          verbose: false # default
          arch: amd64 # allowed values: amd64, arm64
          rootdir: "" # defaults to "PWD"
          workdir: "" # defaults to "PWD/unfor19-awscli"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get WAF IPsets
        run: |
          output=$(aws wafv2 list-ip-sets --scope CLOUDFRONT --region us-east-1)
          blocked_id=$(echo "$output" | jq -r '.IPSets[] | select(.Name=="Blocked") | .Id')
          whitelist_id=$(echo "$output" | jq -r '.IPSets[] | select(.Name=="WhiteList") | .Id')
          blocked_addresses=$(aws wafv2 get-ip-set --scope CLOUDFRONT --region us-east-1 --name Blocked --id $blocked_id | jq -r '.IPSet.Addresses')
          whitelist_addresses=$(aws wafv2 get-ip-set --scope CLOUDFRONT --region us-east-1 --name WhiteList --id $whitelist_id | jq -r '.IPSet.Addresses')
          json_output="{\"Blocked\": $blocked_addresses, \"WhiteList\": $whitelist_addresses}"
          echo $json_output > dev.json
          cp -fr dev.json drawer-app/src

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Build react app
        run: |
          cd drawer-app
          npm install --force
          npm run build
          cd ..

          - name: Upload production-ready build files
          uses: actions/upload-artifact@v2
          with:
            name: production-files
            path: ./drawer-app/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
